id: IA83BAC6F
initial_creation_type: ebook
source_metadata:
  id: KS-GP-02
  title: ༄༅། །མགོན་པོ་ཟླ་འོད་གཞོན་ནུས་མཛད་པའི་ཚོགས་ཆོས་ལེགས་མཛེས་མ་བཞུགས་སོ། །
  author: མཛད་པ་པོ། སྒམ་པོ་པ་བསོད་ནམས་རིན་ཆེན།
  authors: &id001
  - མཛད་པ་པོ། སྒམ་པོ་པ་བསོད་ནམས་རིན་ཆེན།
  sku: KS-GP-02
  cover: KS-GP-02.jpg
  volume: {}
ebook_metadata:
  title: ༄༅། །མགོན་པོ་ཟླ་འོད་གཞོན་ནུས་མཛད་པའི་ཚོགས་ཆོས་ལེགས་མཛེས་མ་བཞུགས་སོ། །
  authors: *id001
  sku: KS-GP-02
  cover: KS-GP-02.jpg
layers:
- Author
- BookTitle
- Chapter
- Citation
- Commentary
